name: Actu

on: 
  issues:
    types: [labeled]

jobs:
  DevOps:
    if: github.event.label.name == 'liens/DevOps'
    runs-on: ubuntu-latest
    steps:
    - name: Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEVOPS }}
      uses: Ilshidur/action-discord@f2373432ba5105bf3ec960c9aaab6c6427a0ad89
      with:
        args: |-
          Une nouvelle actu a été postée par [@{{ EVENT_PAYLOAD.issue.user.login }}]({{ EVENT_PAYLOAD.issue.user.html_url }}) : __***{{ EVENT_PAYLOAD.issue.title }}***__
          {{ EVENT_PAYLOAD.issue.html_url}}
    - name: Project DevOps
      uses: alex-page/github-project-automation-plus@v0.2.3
      with:
        project: DevOps
        column: To Do
        repo-token: ${{ secrets.GH_TOKEN }}

  Kubernetes:
    if: github.event.label.name == 'liens/Kubernetes'
    runs-on: ubuntu-latest
    steps:
      - name: Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_KUBERNETES }}
        uses: Ilshidur/action-discord@f2373432ba5105bf3ec960c9aaab6c6427a0ad89
        with:
          args: |-
            Une nouvelle actu a été postée par [@{{ EVENT_PAYLOAD.issue.user.login }}]({{ EVENT_PAYLOAD.issue.user.html_url }}) : __***{{ EVENT_PAYLOAD.issue.title }}***__
            {{ EVENT_PAYLOAD.issue.html_url}}
      - name: Project
        uses: alex-page/github-project-automation-plus@v0.2.3
        with:
          project: Kubernetes
          column: To Do
          repo-token: ${{ secrets.GH_TOKEN }}
