# This is a basic workflow to help you get started with Actions

name: Actu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  issues:
    types: [labeled]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Discord DevOps
      if: github.event.label.name == 'liens/DevOps'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEVOPS }}
      uses: Ilshidur/action-discord@f2373432ba5105bf3ec960c9aaab6c6427a0ad89
      with:
        args: |-
          Une nouvelle actu a été postée par @{{ EVENT_PAYLOAD.issue.user.login }} : "{{ EVENT_PAYLOAD.issue.title }}"
          {{ EVENT_PAYLOAD.issue.html_url}}
    - name: Discord Kubernetes
      if: github.event.label.name == 'liens/Kubernetes'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_KUBERNETES }}
      uses: Ilshidur/action-discord@f2373432ba5105bf3ec960c9aaab6c6427a0ad89
      with:
        args: 'Une nouvelle actu a été postée par @{{ EVENT_PAYLOAD.issue.user.login }} : "{{ EVENT_PAYLOAD.issue.title }}"'
