name: rss

on:
  schedule:
  - cron: '12 * * * *'

jobs:
  gke:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://cloud.google.com/feeds/kubernetes-engine-release-notes.xml"
        prefix: "[GKE]"
        dry-run: "false"
        lastTime: "92h"
        labels: "liens/Kubernetes"
  aks:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://github.com/Azure/AKS/releases.atom"
        prefix: "[AKS]"
        lastTime: "92h"
        labels: "liens/Kubernetes"
  eks:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://docs.aws.amazon.com/eks/latest/userguide/doc-history.rss"
        prefix: "[EKS]"
        lastTime: "92h"
        labels: "liens/Kubernetes"
