name: rss

on:
  schedule:
  - cron: '*/2 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gke-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: guilhem/rss-issues-action@0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://cloud.google.com/feeds/kubernetes-engine-release-notes.xml"
        prefix: "[GKE] "
        dry-run: "true"
        lastTime: "300h"
