name: Greetings

on:
  issues:
    types: [created]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          :wave: Bienvenue :wave:
          Merci beaucoup pour ta contribution !
